export const passStatusMock = {
  PENDING: "PENDING",
  WAITING: "WAITING",
  ACTIVE: "ACTIVE",
  COMPLETED: "COMPLETED",
  CANCELLED: "CANCELLED",
  DENIED: "DENIED",
  EXPIRED: "EXPIRED",
} as const;
